#============================Jenkins=========================================
[jenkins]
ci/cd-jenkins ansible_host=10.4.3.10


#============================all=========================================

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
